version: '3'

services:
  backend_pokemon:    
    image: jsarangoq/backend_pokemon:1.0.0
    restart: always
    container_name: backend_pokemon
    hostname: backend_pokemon
    ports:
      - 8000:8000

  front_pokemon:    
    image: jsarangoq/frontend_pokemon:1.0.0
    restart: always
    container_name: frontend_pokemon
    hostname: frontend_pokemon
    ports:
      - 3000:3000
